/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package koperasi;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.StringTokenizer;
import java.util.Locale;

/**
 *
 * @author windows
 */
public class Angsuran extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private Connection connection;
    /**
     * Creates new form Angsuran
     */
    public Angsuran() {
        initComponents();
         initTable();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNoPinj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBesar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAngsuran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBunga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        btsimpan = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbangsuran = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtjangka = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttgl = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtke = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TABEL ANGSURAN PINJAMAN ANGGOTA");

        jLabel2.setText("No Kwitansi");

        jLabel3.setText("Tanggal");

        jLabel4.setText("No Pinjaman");

        txtNoPinj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoPinjKeyReleased(evt);
            }
        });

        jLabel5.setText("ID Anggota");

        jLabel6.setText("Besar Pinjaman");

        jLabel7.setText("Angsuran Per Bulan");

        jLabel8.setText("Bunga Per Bulan");

        jLabel9.setText("Jumlah Bayar");

        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btubah.setText("Ubah");
        btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btubahActionPerformed(evt);
            }
        });

        btreset.setText("Reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        btkeluar.setText("Keluar");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });

        tbangsuran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbangsuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbangsuranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbangsuran);

        jLabel10.setText("Jangka");

        jLabel11.setText("Bulan");

        jLabel12.setText("Ke");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtjangka))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNo, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtNoPinj)
                            .addComponent(txtID)
                            .addComponent(txttgl))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAngsuran)
                            .addComponent(txtBunga)
                            .addComponent(txtBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtBesar)
                            .addComponent(txtke)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bthapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btreset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btkeluar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoPinj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBesar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btsimpan)
                            .addComponent(bthapus)
                            .addComponent(btubah)
                            .addComponent(btreset)
                            .addComponent(btkeluar)
                            .addComponent(jLabel10)
                            .addComponent(txtjangka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
        // TODO add your handling code here:
         new MenuUtama().setVisible(true);
    }//GEN-LAST:event_btkeluarActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btresetActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
         String kwitansi = txtNo.getText();
         String tgl = txttgl.getText();
         String no = txtNoPinj.getText();
         String ID = txtID.getText();
         String besar = txtBesar.getText();
         String jangka = txtjangka.getText();
         String ke = txtke.getText();
         String angsuran = txtAngsuran.getText();
         String bunga = txtBunga.getText();
         String bayar = txtBayar.getText();
       

        //masukkan data ke database
        connection = KoperasiDatabase.getConnection();
        String query = "INSERT INTO angsuran"
                + "(No_Kwitansi, Tanggal, Nomor, IDAnggota, Besar, Jangka, Ke, Angsuran, Bunga, Bayar)"
                + "VALUES (?,?,?,?,?,?,?,?,?,?)";

        try {
          PreparedStatement statement= (PreparedStatement) connection.prepareStatement(query);
          
          statement.setString(1, kwitansi);
          statement.setString(2, tgl);
          statement.setString(3, no);
          statement.setString(4, ID);
          statement.setString(5, besar);
          statement.setString(6, jangka);
          statement.setString(7, ke);
          statement.setString(8, angsuran);
          statement.setString(9, bunga);
          statement.setString(10, bayar);
         
          
          statement.executeUpdate();
        } catch (SQLException ex){
          JOptionPane.showMessageDialog(this, "Terjadi error pada saat input data");
          
        } finally {
          loadData();
          reset();
        }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
          int row = tbangsuran.getSelectedRow();
        if (row==-1){
            return;
        }
        
        //mengambil inputan untuk data yg akan diubah
        String kwitansi = (String) tableModel.getValueAt(row, 0);
        
        //lakukan perubahan data ke db
        connection = KoperasiDatabase.getConnection();
        String query = "DELETE FROM angsuran WHERE No_Kwitansi=?";
        
        try {
            PreparedStatement statement = (PreparedStatement) connection.prepareStatement(query);
            String Kwitansi;
            statement.setString(1, kwitansi);
            statement.executeUpdate();            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi error pada saat delete data");
        } finally {
          loadData();  
          reset();
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btubahActionPerformed
        // TODO add your handling code here:
           int row = tbangsuran.getSelectedRow();
        if (row==-1){
            return;
        }
        
        //mengambil inputan untuk data yg akan diubah
        String kwitansi = (String) tableModel.getValueAt(row, 0);
        String tgl = txttgl.getText();
        String no = txtNoPinj.getText();
        String ID = txtID.getText();
        String besar = txtBesar.getText();
        String jangka = txtjangka.getText();
        String ke = txtke.getText();
        String angsuran = txtAngsuran.getText();
        String bunga = txtBunga.getText();
        String bayar = txtBayar.getText();

        //lakukan perubahan data ke database
        connection = KoperasiDatabase.getConnection();
        String query = "UPDATE angsuran SET "
            + "Tanggal=?,Nomor=?, IDAnggota=?, Besar=?, Jangka=?, Ke=?, Angsuran=?,Bunga=?,Bayar=?"
            + "WHERE No_Kwitansi=?";
        try {
            PreparedStatement statement = (PreparedStatement) connection.prepareStatement(query);
            statement.setString(1, kwitansi);
             statement.setString(2, tgl);
            statement.setString(3, no);
            statement.setString(4, ID);
            statement.setString(5, besar);
            statement.setString(6, jangka);
            statement.setString(7, ke);
            statement.setString(8, angsuran);
            statement.setString(9, bunga);
            statement.setString(10, bayar);
            statement.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi error pada saat update data");
        } finally {
            loadData();
            reset();
        }
    }//GEN-LAST:event_btubahActionPerformed

    private void tbangsuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbangsuranMouseClicked
        // TODO add your handling code here:
          int row=tbangsuran.getSelectedRow();
            if (row==-1) {
                return;
            }
        
            //mengambil data dan ditampung
            String kwitansi = (String) tableModel.getValueAt(row, 0);
            String tgl = (String) tableModel.getValueAt(row, 1);
            String no = (String) tableModel.getValueAt(row, 2);
            String ID = (String) tableModel.getValueAt(row, 3);
            String besar = (String) tableModel.getValueAt(row, 4);
            String jangka = (String) tableModel.getValueAt(row, 5);
            String ke = (String) tableModel.getValueAt(row, 6);
            String angsuran = (String) tableModel.getValueAt(row, 7);
            String bunga = (String) tableModel.getValueAt(row, 8);
            String bayar = (String) tableModel.getValueAt(row, 9);
          
            
            //memberi data di setiap inputan
            txtNo.setText(kwitansi);
            txttgl.setText(tgl);
            txtNoPinj.setText(no);
            txtID.setText(ID);
            txtBesar.setText(besar);
            txtjangka.setText(jangka);
            txtke.setText(ke);
            txtAngsuran.setText(angsuran);
            txtBunga.setText(bunga);
            txtBayar.setText(bayar);
         
    }//GEN-LAST:event_tbangsuranMouseClicked

    private void txtNoPinjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPinjKeyReleased
        // TODO add your handling code here:
         try {
          
          String tampil = txtNoPinj.getText();
          
          connection = KoperasiDatabase.getConnection();
        
          String matkul = "SELECT IDAnggota, Besar, Jangka FROM pinjaman WHERE Nomor LIKE '%"+tampil+"%'";

          Statement statement = (Statement) connection.createStatement();
          ResultSet resultSet = statement.executeQuery(matkul);
          
          while (resultSet.next()){
            txtID.setText(resultSet.getString("IDAnggota"));  
             txtBesar.setText(resultSet.getString("Besar"));
              txtjangka.setText(resultSet.getString("Jangka"));
             
          }
          
          resultSet.close(); //menutup result set
          statement.close(); //menutup statement
          
        } catch (SQLException ex) {
          System.out.println(ex.getMessage()); 
    }//GEN-LAST:event_txtNoPinjKeyReleased
    
    Double B, Y, uang, R;
    int J;
    
     uang = Double.parseDouble(txtBesar.getText());
     J = Integer.parseInt(txtjangka.getText());
     
    B = 0.01 * uang;
    R = uang / J;
    Y = R + B;
    
     DecimalFormat angka = new DecimalFormat("###,###");
     txtBunga.setText(""+Double.toString(B));
     txtBayar.setText(""+Double.toString(Y));
     txtAngsuran.setText(""+Double.toString(R));
  
    
    
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Angsuran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton btreset;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton btubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbangsuran;
    private javax.swing.JTextField txtAngsuran;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtBesar;
    private javax.swing.JTextField txtBunga;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtNoPinj;
    private javax.swing.JTextField txtjangka;
    private javax.swing.JTextField txtke;
    private javax.swing.JTextField txttgl;
    // End of variables declaration//GEN-END:variables

private void initTable(){
        tableModel = new DefaultTableModel();
        tbangsuran.setModel(tableModel);
        tableModel.addColumn("No. Kwitansi");
        tableModel.addColumn("Tanggal");
        tableModel.addColumn("No. Pinjaman");
        tableModel.addColumn("ID Anggota");
        tableModel.addColumn("Besar Pinjaman");
        tableModel.addColumn("Ke");
        tableModel.addColumn("Angsuran Per Bulan");
        tableModel.addColumn("Bunga Per Bulan");
        tableModel.addColumn("Jumlah Bayar");
        
    }
    
    private void loadData(){
        //menghapus seluruh data yg ada di tabel
        tableModel.getDataVector().removeAllElements();
        //pemberitahuan tabel telah kosong
        tableModel.fireTableDataChanged();
        
        try{
            connection = KoperasiDatabase.getConnection();
            String query = "SELECT * FROM angsuran";
            
            Statement statement = (Statement) connection.createStatement();
            ResultSet resultSet = statement.executeQuery(query);
            
            //mengisi tabel dgn data hasil query
            while (resultSet.next()){
                Object[] siswa = new Object[10];
                siswa[0] = resultSet.getString("No_kwitansi");
                siswa[1] = resultSet.getString("Tanggal");
                siswa[2] = resultSet.getString("Nomor");
                siswa[3] = resultSet.getString("IDAnggota");
                siswa[4] = resultSet.getString("Besar");
                siswa[5] = resultSet.getString("Jangka");
                siswa[6] = resultSet.getString("Angsuran");
                siswa[7] = resultSet.getString("Ke");
                siswa[8] = resultSet.getString("Bunga");
                siswa[9] = resultSet.getString("Bayar");
                tableModel.addRow(siswa);
            }
            resultSet.close();
            statement.close();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    private void reset(){
        txtNo.setText("");
        txttgl.setText("");
        txtNoPinj.setText("");
        txtID.setText("");
        txtBesar.setText("");
        txtjangka.setText("");
        txtke.setText("");
        txtAngsuran.setText("");
        txtBunga.setText("");
        txtBayar.setText("");
    }
}
